@extends('layouts.front')

@section('content')
    <h1>Mentions légales</h1>

    <p>Merci de lire avec attentions les différentes modalités d’utilisation du présent site avant d’y parcourir ses pages. En vous connectant sur ce site, vous acceptez sans réserves les présentes modalités. Aussi, conformément de l’Article n°6 de la Loi n°2004-575 du 21 Juin 2004 pour la confiance dans l’économie numérique, les responsables du présent site internet stars wars store sont :</p>
    <p>Nom : Martin Prénom : Pierre rue xxx 75010 Paris Email : pierremartin.pro@gmail.com Site Web : pierredesigner.com</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rutrum nunc nec porttitor ullamcorper. Praesent lobortis finibus augue, facilisis viverra tellus efficitur eget. Suspendisse at elementum purus. Curabitur ex mauris, laoreet vitae pulvinar a, euismod sed justo. Sed fermentum finibus neque eu scelerisque. Fusce libero nisl, laoreet eget dui a, pharetra maximus neque. Ut ac cursus leo. Nullam quis tortor eu dolor vehicula sollicitudin. Nam eu molestie quam. Morbi placerat dui ligula, eu ultricies lectus varius vitae. Proin pulvinar nisl sit amet mi volutpat finibus. In vulputate massa a ex consectetur efficitur. Morbi pretium aliquet vestibulum. Nulla facilisi.</p>
    <p>Curabitur condimentum at lectus nec sagittis. Donec dictum vehicula dolor. Etiam pulvinar ipsum orci, vitae maximus arcu ornare vel. Aliquam sapien justo, venenatis quis suscipit quis, pretium vitae turpis. Nunc egestas mauris in sem ornare, quis fermentum mauris tincidunt. Pellentesque euismod ipsum erat, id suscipit tortor interdum in. Morbi tincidunt felis imperdiet, facilisis nunc ac, fringilla urna. Suspendisse vitae pellentesque quam. Phasellus sit amet ligula hendrerit ligula efficitur vehicula.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rutrum nunc nec porttitor ullamcorper. Praesent lobortis finibus augue, facilisis viverra tellus efficitur eget. Suspendisse at elementum purus. Curabitur ex mauris, laoreet vitae pulvinar a, euismod sed justo. Sed fermentum finibus neque eu scelerisque. Fusce libero nisl, laoreet eget dui a, pharetra maximus neque. Ut ac cursus leo. Nullam quis tortor eu dolor vehicula sollicitudin. Nam eu molestie quam. Morbi placerat dui ligula, eu ultricies lectus varius vitae. Proin pulvinar nisl sit amet mi volutpat finibus. In vulputate massa a ex consectetur efficitur. Morbi pretium aliquet vestibulum. Nulla facilisi.</p>
    <p>Curabitur condimentum at lectus nec sagittis. Donec dictum vehicula dolor. Etiam pulvinar ipsum orci, vitae maximus arcu ornare vel. Aliquam sapien justo, venenatis quis suscipit quis, pretium vitae turpis. Nunc egestas mauris in sem ornare, quis fermentum mauris tincidunt. Pellentesque euismod ipsum erat, id suscipit tortor interdum in. Morbi tincidunt felis imperdiet, facilisis nunc ac, fringilla urna. Suspendisse vitae pellentesque quam. Phasellus sit amet ligula hendrerit ligula efficitur vehicula.</p>
@endsection
